---
title: "sdswcodeshiny"
author: "Alaina Liu"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(forcats)
library(MASS)
library(shiny)
library(gridExtra)
```

```{r, eval=TRUE}
arbys <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - Arbys.csv")
blimpie <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - blimpie (1).csv")
buffaloWildWings <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - buffalowildwings (1).csv")
burgerKing <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - burgerking.csv")
carlsJr <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - carsljr (1).csv")
chickFilA <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - chickfila.csv")
chilis <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - chilis (1).csv")
delTaco <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - deltaco (1).csv")
inNOut <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - innout (1).csv")
jackInTheBox <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - JackintheBox.csv")
KFC <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - KFC.csv")
mcdonalds <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - mcdonalds.csv")
popeyes <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - Popeyes.csv")
raisingCanes <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - raisingcanes (1).csv")
sonic <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - Sonic Drive-In.csv")
tacoBell <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - tacobell.csv")
wendys <- read.csv("/Users/alainaliu/Downloads/sdsw-project-main/sdsw restaurants - wendys.csv")
```

```{r, eval=FALSE}
arbys <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - Arbys.csv")
blimpie <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - blimpie (1).csv")
buffaloWildWings <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - buffalowildwings (1).csv")
burgerKing <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - burgerking.csv")
carlsJr <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - carsljr (1).csv")
chickFilA <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - chickfila.csv")
chilis <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - chilis (1).csv")
delTaco <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - deltaco (1).csv")
inNOut <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - innout (1).csv")
jackInTheBox <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - JackintheBox.csv")
KFC <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - KFC.csv")
mcdonalds <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - mcdonalds.csv")
popeyes <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - Popeyes.csv")
raisingCanes <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - raisingcanes (1).csv")
sonic <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - Sonic Drive-In.csv")
tacoBell <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - tacobell.csv")
wendys <- read.csv("/Users/brend/OneDrive/Documents/Calorie Data/sdsw-project-main/sdsw restaurants - wendys.csv")
```

```{r, echo=FALSE}
# combine everything into one dataset
alldata <- bind_rows(arbys, blimpie, buffaloWildWings, burgerKing, carlsJr, chickFilA, chilis, delTaco, inNOut, jackInTheBox, KFC, mcdonalds, popeyes, raisingCanes, sonic, tacoBell, wendys)
# Getting rid of Cane's sauce...
colors <- c("Arby's"="#990000", "Blimpie"="#FF3333", "Buffalo Wild Wings"="#FF6600", "BurgerKing"="#FF9900", "Carl's Jr."="#FFCC00", "Chick-fil-a"="#FFFF00", "Chili's"="#99FF33", "Del Taco"="#66CC00", "In n Out"="#339900", "JackInTheBox"="#006600", "KFC"="#339966", "McDonalds"="#009999", "Popeyes"="#0099CC", "Raising Cane's"="#3399FF", "SonicDrive-In"="#0066CC", "TacoBell"="#0000CC", "Wendy's"="#6600CC")
```

```{r}
checkboxInput("color", 
                label="Color by Restaurant?", 
                value=FALSE)

fluidRow(
  column(6,
    renderPlot({
      price_cal <- ggplot(data=alldata, aes(x=Calories, y=Price))
      if (input$color==TRUE){
        price_cal + geom_point(aes(color=Restaurant)) + scale_color_manual(values=colors)
      } else {
        price_cal + geom_point()
      }
    })),
  column(6,
    renderPlot({
      ss_cal <- ggplot(data=alldata, aes(x=Calories, y=ServingSize))
      if (input$color==TRUE){
        ss_cal + geom_point(aes(color=Restaurant)) + scale_color_manual(values=colors)
      } else {
        ss_cal + geom_point()
      }
    }))
)
```

```{r}
checkboxGroupInput("restaurant",
                   label="Show:",
                   c("Arby's", "Blimpie", "Buffalo Wild Wings", "BurgerKing", "Carl's Jr.", "Chick-fil-a", "Chili's", "Del Taco", "In n Out", "JackInTheBox", "KFC", "McDonalds", "Popeyes", "Raising Cane's", "SonicDrive-In", "TacoBell", "Wendy's"),
                   inline=TRUE
)

fluidRow(
  column(6,
    renderPlot({
      new_alldata <- alldata[alldata$Restaurant==input$restaurant,]
      ggplot(data=new_alldata, aes(x=Calories, y=Price)) + 
        geom_point(aes(color=Restaurant), size=1, alpha=0.5) + 
        scale_color_manual(values=colors) + 
        xlim(0, 2000) + ylim(0, 30)
    })),
  column(6,
    renderPlot({
      new_alldata <- alldata[alldata$Restaurant==input$restaurant,]
      ggplot(data=new_alldata, aes(x=ServingSize, y=Price)) + 
        geom_point(aes(color=Restaurant), size=1, alpha=0.5) + 
        scale_color_manual(values=colors) + 
        xlim(0, 2000) + ylim(0, 30)
  }))
)

```



